name: Build - Dev

on:
  push:
    branches:
    - dev
    paths:
    - "darkness/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Set up py.test
      run: pip3 install pytest requests

    - name: Run Buildx for testing
      run: docker buildx build --tag rangerdigital/darkness:dev --platform linux/amd64 --output type=docker .

    - name: Run Darkness container for testing
      run: docker run --name darkness -p 127.0.0.1:5000:8000 -d rangerdigital/darkness:dev

    - name: Run all the tests
      run: sleep 5; python3 -m pytest

    - name: Setup Tmate session
      uses: mxschmitt/action-tmate@v1
      if: failure()

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Buildx with all platforms
      run: docker buildx build --tag rangerdigital/darkness:dev --platform linux/amd64,linux/arm64,linux/arm/v7 --output type=registry .
